title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs
color_scheme: dark


url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


  collections:
  general:
    permalink: "/:collection/:path/"
    output: true
  game:
    permalink: "/:collection/:path/"
    output: true
  community:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    general:
      name: General
    game:
      name: Game
    community:
      name: Community
